stages:
  prepare:
    cmd: venv/bin/python prepare.py
    deps:
      - data/big_data.csv
      - prepare.py
    outs:
      - data/processed/X.csv
      - data/processed/y.csv


  train:
    cmd: venv/bin/python train.py
    deps:
      - data/processed/X.csv
      - data/processed/y.csv
      - train.py
    outs:
      - model.pkl
